# Generated by Django 3.2.4 on 2021-06-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='penom',
            new_name='prenom',
        ),
    ]
