# Generated by Django 3.2.4 on 2021-06-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_penom_utilisateur_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumissin',
            name='etat',
            field=models.BooleanField(),
        ),
    ]
