# Generated by Django 3.2.4 on 2021-06-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_projet_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='membre',
            field=models.ManyToManyField(to='app.Utilisateur'),
        ),
    ]
